name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Docker build caching based on
# https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-pipeline-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-pipeline-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: airtable-export
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build-monitoring-freshcf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-monitoring-freshcf-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-monitoring-freshcf-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: monitoring/freshcf/Dockerfile
          push: false
          tags: monitoring-freshcf
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache