name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python exporter tool
      run: sudo apt install -y python3-pip python3-setuptools && sudo pip3 install airtable-export

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      working-directory: sanitize

    - name: Run
      run: ./sync.sh
      env:
        AIRTABLE_KEY: ${{ secrets.airtable_key }}

    - name: Publish
      uses: actions-hub/gcloud@324.0.0
      env:
        PROJECT_ID: cavaccineinventory
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: "-h \"Cache-Control:public, max-age=300\" cp -Z airtable/safe/Locations.json gs://cavaccineinventory-sitedata/airtable-staging/Location.json"
        cli: gsutil
